# Generated by Django 3.2.19 on 2024-01-10 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20240111_0154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='password2',
        ),
    ]
