# Generated by Django 3.2.19 on 2024-01-11 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_manager_company_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
