# Generated by Django 3.2.19 on 2024-01-10 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_remove_company_password2'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
