# Generated by Django 3.2.19 on 2024-01-10 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_company_is_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='is_company',
            field=models.BooleanField(default=False),
        ),
    ]
