# Generated by Django 3.2.19 on 2024-01-10 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_myuser_is_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='is_company',
        ),
    ]
